### ISSUE TITLE
What is the tool/package/theme you used for these beautiful code blocks?

### ISSUE THREAD

**Issue by nyngwang** [metachris/website#1]
Do you mind guiding me about how you achieve these beautiful code blocks?

![image](https://github.com/metachris/website/assets/24765272/5f267c4f-2a26-4ed1-928e-1ab04fd287e8)

**Comment by metachris** [comment]
I think it's the default for the theme I've been building on: https://themes.gohugo.io/themes/hugo-coder/

**Comment by nyngwang** [comment]
Thank you ;) Let me close this thread myself.
